### ISSUE TITLE
Construct preview URLs dynamically from branch name

### ISSUE THREAD

**Issue by mnyrop** [mnyrop/iiifc-theme#20]
Follow up question: do branches need to be "paired" post-sprint?
e.g., 
```yml 
root_url:       'https://preview.iiif.io/root/wireframe/'
api_url:        'https://preview.iiif.io/api/wireframe/api'
```

In other words, can we override `api_url` only on preview deploy for the `api` repo?

**Comment by mnyrop** [comment]
... and integrate ci tests such that`baseurl`usage can expose link issues. see: https://github.com/mnyrop/iiifc-theme/issues/18#issuecomment-881505988

**Comment by hadro** [comment]
I don't know the answer to this question so I will tag in @glenrobson

**Comment by mnyrop** [comment]
another quick question: can i get rid of the files in [`/config`](https://github.com/IIIF/api/tree/wireframe/config) ? or will they be used post-migration?

**Comment by mnyrop** [comment]
Open PR: https://github.com/IIIF/api/pull/2026

**Comment by glenrobson** [comment]
I've removed `config` in https://github.com/IIIF/api/pull/2027 as you're right this is no longer needed. `scripts` is a little more complicated and relates to how we retain the JSON checks. I'm sure it could be extracted to another repo and some of the files are out of date and could be removed.
