### ISSUE TITLE
Spec page layout should not have light blue body background

### ISSUE THREAD

**Issue by hadro** [mnyrop/iiifc-theme#22]
As discussed, should either be white or $grey per the design comps:
https://zpl.io/2GjKrrd

**Comment by mnyrop** [comment]
@hadro i just confirmed the background *is* currently white; the blue table heading is just so pale that it doesn't stand out. 

PR #29 makes the blue `th` elements stand out more. Please let me know if there are other tweaks I can add to the PR before merging? I can use the light grey instead if preferable.

**Comment by hadro** [comment]
Yes, this looks great! Nothing further now on this front -- will merge in.
