### ISSUE TITLE
How to handle spec page content without TOC elements?

### ISSUE THREAD

**Issue by hadro** [mnyrop/iiifc-theme#9]
How should we handle `spec` layout pages that don't have any headings, and which therefore don't have a use for the TOC sidebar? Make TOC conditional, or just a slightly modified layout? 
A few examples: 
https://preview.iiif.io/api/wireframe/api/annex/notes/rotation/
https://preview.iiif.io/api/wireframe/api/annex/

**Comment by hadro** [comment]
Ok, I think this one can be handled just by using the "page" layout -- not sure why that didn't occur to me before.

**Comment by mnyrop** [comment]
@hadro using `page` makes sense, but I can still work on conditional logic to make it easier for editors and prevent empty TOC bugs...? Just let me know if it's worth it and I will reopen this ticket.
